language: node_js
os: windows
node_js:
  - 'stable'
sudo: false
notifications:
  email: false
cache:
  npm: true
  directories:
    - 'node_modules'
script:
  - npm run
  - npm install .
  - toush test/engines/henry.js,thomas.js test/controllers/fat.js,thin.js

deploy:
  provider: npm
  on:
    branch: prod
